const colleges = {
  0: "Alabama A & M University",
  1: "University of Alabama at Birmingham",
  3: "University of Alabama in Huntsville",
  4: "Alabama State University",
  5: "The University of Alabama",
  7: "Athens State University",
  8: "Auburn University at Montgomery",
  9: "Auburn University",
  10: "Birmingham-Southern College",
  12: "South University-Montgomery",
  15: "Faulkner University",
  22: "Huntingdon College",
  23: "Heritage Christian University",
  26: "Jacksonville State University",
  29: "Judson College",
  31: "University of West Alabama",
  34: "Miles College",
  35: "University of Mobile",
  36: "University of Montevallo",
  38: "University of North Alabama",
  40: "Oakwood University",
  43: "Samford University",
  44: "Selma University",
  47: "University of South Alabama",
  48: "Spring Hill College",
  49: "Stillman College",
  50: "Talladega College",
  52: "Troy University",
  53: "Tuskegee University",
  54: "United States Sports Academy",
  56: "University of Alaska Anchorage",
  57: "Alaska Bible College",
  58: "University of Alaska Fairbanks",
  60: "Alaska Pacific University",
  72: "Arizona State University-Tempe",
  74: "University of Arizona",
  75: "Southwest University of Visual Arts-Tucson",
  84: "Embry-Riddle Aeronautical University-Prescott",
  87: "Grand Canyon University",
  93: "Northern Arizona University",
  95: "Ottawa University-Phoenix",
  101: "Prescott College",
  107: "Arizona Christian University",
  111: "University of Arkansas at Little Rock",
  112: "University of Arkansas for Medical Sciences",
  116: "Lyon College",
  119: "University of Arkansas",
  120: "University of Arkansas at Pine Bluff",
  122: "Arkansas State University-Main Campus",
  123: "Arkansas Tech University",
  128: "University of Central Arkansas",
  129: "Central Baptist College",
  131: "Crowley's Ridge College",
  138: "Harding University",
  139: "Henderson State University",
  140: "Hendrix College",
  143: "John Brown University",
  151: "Ouachita Baptist University",
  154: "University of the Ozarks",
  156: "Philander Smith College",
  166: "Williams Baptist University",
  168: "Southern Arkansas University Main Campus",
  171: "University of Arkansas-Fort Smith",
  172: "Academy of Art University",
  186: "Art Center College of Design",
  189: "Azusa Pacific University",
  193: "Bethesda University",
  194: "Biola University",
  198: "California Institute of Integral Studies",
  200: "California Baptist University",
  201: "California College of the Arts",
  203: "California Institute of Technology",
  204: "California Lutheran University",
  205: "California Polytechnic State University-San Luis Obispo",
  207: "California State University-Bakersfield",
  208: "California State University-Stanislaus",
  209: "California State University-San Bernardino",
  210: "California State Polytechnic University-Pomona",
  211: "California State University-Chico",
  212: "California State University-Dominguez Hills",
  213: "California State University-Fresno",
  214: "California State University-Fullerton",
  215: "California State University-East Bay",
  216: "California State University-Long Beach",
  217: "California State University-Los Angeles",
  218: "California State University-Northridge",
  219: "California State University-Sacramento",
  220: "University of California-Berkeley",
  221: "University of California-Davis",
  222: "University of California-Irvine",
  223: "University of California-Los Angeles",
  224: "University of California-Riverside",
  225: "University of California-San Diego",
  227: "University of California-Santa Barbara",
  228: "University of California-Santa Cruz",
  229: "Sofia University",
  231: "California Christian College",
  234: "California Institute of the Arts",
  235: "California State University Maritime Academy",
  251: "Chapman University",
  253: "Concordia University-Irvine",
  254: "San Diego Christian College",
  260: "Claremont McKenna College",
  264: "Cogswell College",
  268: "Columbia College Hollywood",
  280: "Design Institute of San Diego",
  282: "Dominican University of California",
  302: "Fresno Pacific University",
  309: "Golden Gate University-San Francisco",
  315: "Harvey Mudd College",
  317: "Holy Names University",
  319: "Humboldt State University",
  320: "Humphreys University-Stockton and Modesto Campuses",
  327: "John F. Kennedy University",
  328: "American Jewish University",
  330: "Life Pacific University",
  331: "University of La Verne",
  332: "Laguna College of Art and Design",
  338: "Lincoln University",
  339: "Southern California Seminary",
  340: "La Sierra University",
  341: "Loma Linda University",
  349: "The Master's University and Seminary",
  354: "Loyola Marymount University",
  364: "Menlo College",
  367: "Mills College",
  373: "Middlebury Institute of International Studies at Monterey",
  377: "Mount Saint Mary's University",
  382: "National University",
  384: "Newschool of Architecture and Design",
  390: "Notre Dame de Namur University",
  391: "Occidental College",
  394: "Otis College of Art and Design",
  396: "Hope International University",
  398: "Palo Alto University",
  399: "Pacific Oaks College",
  401: "Pacific States University",
  402: "Pacific Union College",
  403: "University of the Pacific",
  407: "Pepperdine University",
  408: "Pitzer College",
  410: "Point Loma Nazarene University",
  411: "Pomona College",
  417: "University of Redlands",
  427: "Samuel Merritt University",
  431: "San Diego State University",
  432: "University of San Diego",
  433: "San Francisco Art Institute",
  435: "San Francisco State University",
  437: "University of San Francisco",
  441: "William Jessup University",
  443: "San Jose State University",
  448: "Santa Clara University",
  452: "Scripps College",
  454: "Shasta Bible College and Graduate School",
  459: "Simpson University",
  464: "Saint Mary's College of California",
  466: "Sonoma State University",
  469: "Vanguard University of Southern California",
  475: "Southern California Institute of Architecture",
  476: "University of Southern California",
  480: "Thomas Aquinas College",
  496: "Westmont College",
  497: "Whittier College",
  498: "Woodbury University",
  501: "Yeshiva Ohr Elchonon Chabad West Coast Talmudical Seminary",
  508: "University of Colorado Denver/Anschutz Medical Campus",
  509: "University of Colorado Colorado Springs",
  511: "University of Colorado Boulder",
  512: "Colorado Christian University",
  513: "Colorado College",
  517: "Colorado School of Mines",
  519: "Colorado State University-Fort Collins",
  520: "Colorado Technical University-Colorado Springs",
  527: "University of Denver",
  529: "Fort Lewis College",
  534: "Colorado Mesa University",
  535: "Metropolitan State University of Denver",
  537: "Naropa University",
  538: "Nazarene Bible College",
  540: "University of Northern Colorado",
  546: "Regis University",
  547: "Rocky Mountain College of Art and Design",
  549: "Colorado State University-Pueblo",
  554: "United States Air Force Academy",
  556: "Western Colorado University",
  557: "Albertus Magnus College",
  561: "University of Bridgeport",
  562: "Central Connecticut State University",
  565: "Connecticut College",
  567: "University of Connecticut",
  570: "Eastern Connecticut State University",
  571: "Fairfield University",
  577: "University of Hartford",
  578: "Holy Apostles College and Seminary",
  583: "Mitchell College",
  587: "University of New Haven",
  590: "Paier College of Art Inc",
  592: "Post University",
  594: "Quinnipiac University",
  595: "Sacred Heart University",
  596: "University of Saint Joseph",
  598: "Southern Connecticut State University",
  600: "Trinity College",
  602: "United States Coast Guard Academy",
  603: "Wesleyan University",
  604: "Western Connecticut State University",
  605: "Yale University",
  609: "Delaware State University",
  610: "University of Delaware",
  611: "Goldey-Beacom College",
  613: "Wesley College",
  614: "Wilmington University",
  615: "American University",
  616: "The Catholic University of America",
  617: "University of the District of Columbia",
  619: "Gallaudet University",
  620: "George Washington University",
  621: "Georgetown University",
  622: "Howard University",
  623: "Strayer University-District of Columbia",
  625: "Trinity Washington University",
  628: "The Baptist College of Florida",
  629: "Barry University",
  630: "Bethune-Cookman University",
  631: "Lynn University",
  635: "Carlos Albizu University-Miami",
  637: "Johnson University Florida",
  638: "University of Central Florida",
  643: "South University-West Palm Beach",
  644: "Eckerd College",
  646: "Edward Waters College",
  647: "Embry-Riddle Aeronautical University-Daytona Beach",
  648: "Florida Agricultural and Mechanical University",
  649: "Florida Atlantic University",
  651: "Flagler College-St Augustine",
  656: "AdventHealth University",
  657: "Florida Institute of Technology",
  659: "Florida International University",
  661: "Florida Memorial University",
  664: "Florida Southern College",
  665: "Florida State University",
  667: "University of Florida",
  669: "Full Sail University",
  674: "Hobe Sound Bible College",
  679: "AI Miami International University of Art and Design",
  680: "Jacksonville University",
  690: "Luther Rice College & Seminary",
  695: "Trinity International University-Florida",
  698: "University of Miami",
  703: "University of North Florida",
  704: "Nova Southeastern University",
  707: "Palm Beach Atlantic University",
  716: "Ringling College of Art and Design",
  718: "Rollins College",
  720: "Saint Leo University",
  727: "St. John Vianney College Seminary",
  730: "University of South Florida-Main Campus",
  731: "St. Thomas University",
  732: "Stetson University",
  733: "Southeastern University",
  737: "Talmudic College of Florida",
  739: "The University of Tampa",
  742: "Trinity Baptist College",
  743: "Trinity College of Florida",
  746: "Warner University",
  748: "Webber International University",
  749: "Rasmussen College-Florida",
  750: "The University of West Florida",
  756: "Agnes Scott College",
  762: "The Art Institute of Atlanta",
  765: "Point University",
  769: "Clark Atlanta University",
  771: "Berry College",
  772: "Beulah Heights University",
  773: "Brenau University",
  774: "Brewton-Parker College",
  778: "Clayton State University",
  781: "Columbus State University",
  783: "Covenant College",
  784: "Dalton State College",
  786: "South University-Savannah",
  788: "Emmanuel College",
  789: "Emory University",
  791: "Fort Valley State University",
  793: "Georgia Institute of Technology-Main Campus",
  794: "Georgia Southwestern State University",
  795: "Georgia College & State University",
  796: "Georgia Southern University",
  797: "Georgia State University",
  798: "University of Georgia",
  805: "LaGrange College",
  807: "Life University",
  809: "Herzing University-Atlanta",
  810: "Mercer University",
  811: "Morehouse College",
  814: "Oglethorpe University",
  815: "Paine College",
  816: "Piedmont College",
  818: "Reinhardt University",
  820: "Savannah College of Art and Design",
  821: "Savannah State University",
  822: "Shorter University",
  825: "Spelman College",
  826: "Thomas University",
  827: "Toccoa Falls College",
  828: "Truett McConnell University",
  830: "Valdosta State University",
  831: "Wesleyan College",
  832: "University of West Georgia",
  833: "Young Harris College",
  834: "Chaminade University of Honolulu",
  835: "University of Hawaii at Hilo",
  836: "University of Hawaii at Manoa",
  838: "Hawaii Pacific University",
  845: "University of Hawaii-West Oahu",
  848: "Boise Bible College",
  849: "Boise State University",
  851: "Idaho State University",
  852: "University of Idaho",
  853: "The College of Idaho",
  854: "Lewis-Clark State College",
  858: "Northwest Nazarene University",
  860: "Brigham Young University-Idaho",
  863: "American Academy of Art",
  865: "School of the Art Institute of Chicago",
  866: "Augustana College",
  867: "Aurora University",
  872: "Blackburn College",
  873: "Blessing Rieman College of Nursing and Health Sciences",
  875: "Bradley University",
  888: "Chicago State University",
  890: "University of Chicago",
  898: "Columbia College Chicago",
  899: "Concordia University-Chicago",
  903: "DePaul University",
  906: "East-West University",
  907: "Eastern Illinois University",
  909: "Elmhurst College",
  910: "Eureka College",
  915: "Governors State University",
  917: "Greenville University",
  921: "Hebrew Theological College",
  924: "University of Illinois at Chicago",
  925: "Benedictine University",
  927: "University of Illinois at Urbana-Champaign",
  928: "Illinois Wesleyan University",
  930: "Illinois College",
  932: "Illinois Institute of Technology",
  933: "Illinois State University",
  940: "Judson University",
  944: "Knox College",
  947: "Lake Forest College",
  950: "Lakeview College of Nursing",
  952: "Lewis University",
  953: "Lincoln Christian University",
  954: "Lincoln College",
  957: "Loyola University Chicago",
  959: "Trinity College of Nursing & Health Sciences",
  962: "MacMurray College",
  965: "McKendree University",
  967: "Methodist College",
  969: "Millikin University",
  970: "Monmouth College",
  971: "Moody Bible Institute",
  976: "National Louis University",
  977: "National University of Health Sciences",
  979: "North Central College",
  980: "North Park University",
  982: "Northern Illinois University",
  983: "Northwestern University",
  984: "Northeastern Illinois University",
  987: "Olivet Nazarene University",
  990: "Principia College",
  992: "Quincy University",
  995: "Robert Morris University Illinois",
  998: "Rockford University",
  999: "Roosevelt University",
  1000: "Dominican University",
  1001: "Rush University",
  1002: "Saint Francis Medical Center College of Nursing",
  1003: "University of St Francis",
  1004: "St. John's College-Department of Nursing",
  1005: "Saint Xavier University",
  1006: "University of Illinois at Springfield",
  1015: "Saint Anthony College of Nursing",
  1017: "Southern Illinois University-Carbondale",
  1018: "Southern Illinois University-Edwardsville",
  1020: "Telshe Yeshiva-Chicago",
  1023: "Trinity Christian College",
  1024: "Trinity International University-Illinois",
  1027: "VanderCook College of Music",
  1029: "Resurrection University",
  1030: "Western Illinois University",
  1031: "Wheaton College",
  1034: "Anderson University",
  1035: "Ball State University",
  1036: "Bethel University",
  1037: "Butler University",
  1038: "Calumet College of Saint Joseph",
  1043: "DePauw University",
  1046: "Earlham College",
  1047: "University of Evansville",
  1048: "Franklin College",
  1049: "Goshen College",
  1050: "Grace College and Theological Seminary",
  1051: "Hanover College",
  1053: "Holy Cross College",
  1055: "Huntington University",
  1057: "Purdue University Fort Wayne",
  1058: "Indiana University-Purdue University-Indianapolis",
  1059: "University of Indianapolis",
  1060: "Indiana Institute of Technology",
  1061: "University of Southern Indiana",
  1062: "Indiana State University",
  1063: "Indiana University-Kokomo",
  1064: "Indiana University-South Bend",
  1065: "Indiana University-Bloomington",
  1066: "Indiana University-Northwest",
  1067: "Indiana University-Southeast",
  1068: "Indiana University-East",
  1075: "Manchester University",
  1076: "Marian University",
  1077: "Indiana Wesleyan University-Marion",
  1078: "Martin University",
  1082: "University of Notre Dame",
  1083: "Oakland City University",
  1087: "Rose-Hulman Institute of Technology",
  1088: "University of Saint Francis-Fort Wayne",
  1089: "Saint Mary-of-the-Woods College",
  1090: "Saint Mary's College",
  1093: "Taylor University",
  1094: "Trine University",
  1095: "Valparaiso University",
  1098: "Wabash College",
  1099: "Allen College",
  1100: "Briar Cliff University",
  1101: "Buena Vista University",
  1104: "Central College",
  1105: "Clarke University",
  1106: "Coe College",
  1107: "Cornell College",
  1110: "Divine Word College",
  1111: "Dordt University",
  1112: "Drake University",
  1113: "University of Dubuque",
  1117: "Faith Baptist Bible College and Theological Seminary",
  1119: "Graceland University-Lamoni",
  1120: "Grand View University",
  1121: "Grinnell College",
  1122: "Purdue University Global-Mason City",
  1123: "Purdue University Global-Cedar Rapids",
  1133: "Iowa State University",
  1134: "Iowa Wesleyan University",
  1136: "University of Iowa",
  1142: "Loras College",
  1143: "Luther College",
  1144: "Maharishi University of Management",
  1146: "Mercy College of Health Sciences",
  1147: "Morningside College",
  1148: "Mount Mercy University",
  1151: "University of Northern Iowa",
  1152: "Northwestern College",
  1157: "Palmer College of Chiropractic",
  1159: "Saint Ambrose University",
  1163: "Simpson College",
  1169: "Upper Iowa University",
  1170: "Waldorf University",
  1171: "Wartburg College",
  1175: "William Penn University",
  1177: "Baker University",
  1179: "Benedictine College",
  1180: "Bethany College",
  1181: "Bethel College-North Newton",
  1183: "Central Christian College of Kansas",
  1190: "Emporia State University",
  1192: "Fort Hays State University",
  1193: "Barclay College",
  1194: "Friends University",
  1207: "University of Kansas",
  1208: "Newman University",
  1210: "Kansas State University",
  1211: "Kansas Wesleyan University",
  1215: "Manhattan Christian College",
  1216: "McPherson College",
  1217: "MidAmerica Nazarene University",
  1221: "Ottawa University-Ottawa",
  1222: "Ottawa University-Kansas City",
  1223: "Pittsburg State University",
  1225: "University of Saint Mary",
  1228: "Southwestern College",
  1229: "Sterling College",
  1230: "Tabor College",
  1231: "Washburn University",
  1233: "Wichita State University",
  1235: "Alice Lloyd College",
  1236: "Asbury University",
  1240: "Bellarmine University",
  1241: "Berea College",
  1244: "Brescia University",
  1245: "Campbellsville University",
  1247: "Centre College",
  1248: "Clear Creek Baptist Bible College",
  1251: "University of the Cumberlands",
  1252: "Eastern Kentucky University",
  1255: "Georgetown College",
  1264: "Kentucky Mountain Bible College",
  1265: "Kentucky State University",
  1266: "Kentucky Wesleyan College",
  1267: "University of Kentucky",
  1268: "Kentucky Christian University",
  1270: "Lindsey Wilson College",
  1271: "University of Louisville",
  1275: "Midway University",
  1276: "Morehead State University",
  1277: "Murray State University",
  1279: "Northern Kentucky University",
  1281: "University of Pikeville",
  1289: "The Southern Baptist Theological Seminary",
  1290: "Spalding University",
  1292: "Thomas More University",
  1293: "Transylvania University",
  1295: "Union College",
  1296: "Western Kentucky University",
  1302: "Centenary College of Louisiana",
  1309: "Dillard University",
  1311: "Grambling State University",
  1315: "Louisiana State University Health Sciences Center-New Orleans",
  1316: "Louisiana State University-Alexandria",
  1317: "Louisiana State University and Agricultural & Mechanical College",
  1319: "Louisiana State University-Shreveport",
  1323: "Louisiana College",
  1325: "Louisiana Tech University",
  1326: "Loyola University New Orleans",
  1327: "McNeese State University",
  1328: "University of New Orleans",
  1330: "Nicholls State University",
  1331: "University of Louisiana at Monroe",
  1333: "Northwestern State University of Louisiana",
  1334: "University of Holy Cross",
  1335: "Franciscan Missionaries of Our Lady University",
  1340: "Saint Joseph Seminary College",
  1347: "Southeastern Louisiana University",
  1348: "Southern University and A & M College",
  1349: "Southern University at New Orleans",
  1351: "University of Louisiana at Lafayette",
  1353: "Tulane University of Louisiana",
  1354: "Xavier University of Louisiana",
  1356: "Purdue University Global-Lewiston",
  1357: "College of the Atlantic",
  1358: "Bates College",
  1360: "Bowdoin College",
  1363: "Colby College",
  1367: "University of Maine at Augusta",
  1368: "University of Maine at Farmington",
  1369: "University of Maine at Fort Kent",
  1370: "University of Maine at Machias",
  1371: "University of Maine",
  1372: "Maine Maritime Academy",
  1373: "University of Maine at Presque Isle",
  1374: "University of New England",
  1377: "Maine College of Art",
  1378: "Saint Joseph's College of Maine",
  1381: "University of Southern Maine",
  1382: "Thomas College",
  1383: "Unity College",
  1390: "University of Baltimore",
  1391: "Bowie State University",
  1392: "Capitol Technology University",
  1396: "Washington Adventist University",
  1397: "Coppin State University",
  1401: "Frostburg State University",
  1403: "Goucher College",
  1404: "Purdue University Global-Hagerstown",
  1407: "Hood College",
  1410: "Johns Hopkins University",
  1412: "Loyola University Maryland",
  1413: "University of Maryland Global Campus",
  1414: "University of Maryland Baltimore",
  1415: "University of Maryland-Baltimore County",
  1416: "University of Maryland-College Park",
  1417: "Maryland Institute College of Art",
  1418: "University of Maryland Eastern Shore",
  1422: "Morgan State University",
  1423: "Mount St. Mary's University",
  1424: "Ner Israel Rabbinical College",
  1426: "Notre Dame of Maryland University",
  1430: "Salisbury University",
  1431: "St. Mary's College of Maryland",
  1432: "St. John's College",
  1433: "Towson University",
  1435: "United States Naval Academy",
  1436: "Stevenson University",
  1437: "Washington College",
  1438: "McDaniel College",
  1440: "Hult International Business School",
  1442: "American International College",
  1443: "Amherst College",
  1445: "Anna Maria College",
  1447: "Assumption College",
  1448: "Babson College",
  1450: "Boston Baptist College",
  1451: "Bay Path University",
  1452: "Bay State College",
  1454: "Becker College",
  1455: "Bentley University",
  1456: "Berklee College of Music",
  1459: "Boston Architectural College",
  1461: "Boston College",
  1462: "Boston University",
  1463: "Brandeis University",
  1464: "Bridgewater State University",
  1468: "Cambridge College",
  1472: "Clark University",
  1474: "Curry College",
  1476: "Dean College",
  1479: "Eastern Nazarene College",
  1480: "Emerson College",
  1481: "Emmanuel College",
  1482: "Endicott College",
  1484: "Fisher College",
  1485: "Fitchburg State University",
  1486: "Framingham State University",
  1488: "Gordon College",
  1491: "Hampshire College",
  1492: "Harvard University",
  1494: "Hellenic College-Holy Cross Greek Orthodox School of Theology",
  1495: "College of the Holy Cross",
  1497: "Lasell University",
  1499: "Lesley University",
  1502: "University of Massachusetts-Lowell",
  1503: "University of Massachusetts-Amherst",
  1504: "University of Massachusetts-Boston",
  1506: "MCPHS University",
  1507: "Massachusetts College of Art and Design",
  1508: "Massachusetts Institute of Technology",
  1509: "Massachusetts Maritime Academy",
  1514: "Merrimack College",
  1515: "MGH Institute of Health Professions",
  1517: "Montserrat College of Art",
  1518: "Mount Holyoke College",
  1521: "The New England Conservatory of Music",
  1522: "New England College of Optometry",
  1525: "Newbury College",
  1526: "Nichols College",
  1527: "Massachusetts College of Liberal Arts",
  1530: "Northeastern University",
  1532: "College of Our Lady of the Elms",
  1533: "Pine Manor College",
  1537: "Regis College",
  1539: "Saint John's Seminary",
  1540: "Salem State University",
  1542: "Simmons University",
  1544: "Smith College",
  1546: "Springfield College",
  1548: "University of Massachusetts-Dartmouth",
  1549: "Stonehill College",
  1550: "Suffolk University",
  1552: "Tufts University",
  1553: "Wellesley College",
  1554: "Wentworth Institute of Technology",
  1555: "Western New England University",
  1556: "Westfield State University",
  1557: "Wheaton College",
  1558: "Williams College",
  1559: "Worcester Polytechnic Institute",
  1560: "Worcester State University",
  1561: "Adrian College",
  1562: "Albion College",
  1565: "Alma College",
  1567: "Andrews University",
  1568: "Aquinas College",
  1572: "Calvin University",
  1576: "Central Michigan University",
  1579: "Cleary University",
  1580: "Concordia University-Ann Arbor",
  1582: "College for Creative Studies",
  1583: "Davenport University",
  1589: "University of Detroit Mercy",
  1592: "Eastern Michigan University",
  1594: "Ferris State University",
  1597: "Kettering University",
  1599: "Grace Christian University",
  1600: "Cornerstone University",
  1602: "Grand Valley State University",
  1603: "Great Lakes Christian College",
  1605: "Hillsdale College",
  1606: "Hope College",
  1608: "Kalamazoo College",
  1614: "Lake Superior State University",
  1616: "Lawrence Technological University",
  1619: "Madonna University",
  1620: "Marygrove College",
  1621: "Rochester University",
  1622: "University of Michigan-Ann Arbor",
  1624: "Michigan State University",
  1625: "Michigan Technological University",
  1626: "University of Michigan-Dearborn",
  1627: "University of Michigan-Flint",
  1633: "Northern Michigan University",
  1635: "Northwood University",
  1637: "Oakland University",
  1638: "Olivet College",
  1640: "Kuyper College",
  1645: "Saginaw Valley State University",
  1647: "Siena Heights University",
  1651: "Spring Arbor University",
  1653: "Finlandia University",
  1656: "Walsh College",
  1659: "Wayne State University",
  1662: "Western Michigan University",
  1670: "Augsburg University",
  1673: "Bemidji State University",
  1674: "Bethany Lutheran College",
  1675: "Bethel University",
  1678: "Carleton College",
  1679: "Concordia College at Moorhead",
  1680: "Concordia University-Saint Paul",
  1682: "Martin Luther College",
  1687: "Gustavus Adolphus College",
  1688: "Hamline University",
  1696: "Macalester College",
  1698: "Minnesota State University-Mankato",
  1701: "Metropolitan State University",
  1702: "University of Minnesota-Twin Cities",
  1703: "University of Minnesota-Crookston",
  1705: "Minneapolis College of Art and Design",
  1707: "Herzing University-Minneapolis",
  1709: "University of Minnesota-Duluth",
  1710: "University of Minnesota-Morris",
  1712: "Minnesota State University Moorhead",
  1716: "North Central University",
  1718: "University of Northwestern-St Paul",
  1720: "Oak Hills Christian College",
  1724: "College of Saint Benedict",
  1726: "Saint Cloud State University",
  1727: "Saint Johns University",
  1728: "Saint Mary's University of Minnesota",
  1729: "St Olaf College",
  1730: "Crown College",
  1731: "The College of Saint Scholastica",
  1732: "University of St Thomas",
  1734: "St Catherine University",
  1737: "Southwest Minnesota State University",
  1744: "Winona State University",
  1747: "Alcorn State University",
  1748: "Belhaven University",
  1749: "Blue Mountain College",
  1755: "Delta State University",
  1763: "Jackson State University",
  1766: "Millsaps College",
  1768: "University of Mississippi",
  1769: "Mississippi University for Women",
  1770: "Mississippi Valley State University",
  1771: "Mississippi College",
  1774: "Mississippi State University",
  1778: "Rust College",
  1779: "Southeastern Baptist College",
  1781: "University of Southern Mississippi",
  1783: "Tougaloo College",
  1785: "William Carey University",
  1787: "Avila University",
  1788: "Baptist Bible College",
  1790: "Cox College",
  1791: "Calvary University",
  1793: "Central Christian College of the Bible",
  1794: "Central Methodist University-College of Liberal Arts and Sciences",
  1795: "University of Central Missouri",
  1797: "Cleveland University-Kansas City",
  1799: "Columbia College",
  1800: "Conception Seminary College",
  1805: "Culver-Stockton College",
  1806: "Drury University",
  1811: "Evangel University",
  1812: "Fontbonne University",
  1815: "Hannibal-LaGrange University",
  1816: "Harris-Stowe State University",
  1821: "Barnes-Jewish College Goldfarb School of Nursing",
  1822: "Kansas City Art Institute",
  1823: "Kenrick Glennon Seminary",
  1827: "Lincoln University",
  1828: "Lindenwood University",
  1830: "Logan University",
  1833: "Maryville University of Saint Louis",
  1837: "Midwestern Baptist Theological Seminary",
  1839: "Missouri Baptist University",
  1840: "Missouri Southern State University",
  1841: "Missouri Valley College",
  1842: "Missouri Western State University",
  1843: "University of Missouri-Columbia",
  1844: "University of Missouri-Kansas City",
  1845: "Missouri University of Science and Technology",
  1846: "University of Missouri-St Louis",
  1851: "Truman State University",
  1852: "Northwest Missouri State University",
  1853: "Ozark Christian College",
  1854: "College of the Ozarks",
  1855: "Park University",
  1856: "Stevens-The Institute of Business & Arts",
  1859: "Research College of Nursing",
  1860: "Rockhurst University",
  1862: "Saint Louis University",
  1866: "Saint Louis Christian College",
  1867: "St. Louis College of Pharmacy",
  1870: "Southwest Baptist University",
  1872: "Saint Luke's College of Health Sciences",
  1875: "Stephens College",
  1876: "Southeast Missouri State University",
  1877: "Missouri State University-Springfield",
  1881: "Washington University in St Louis",
  1882: "Webster University",
  1883: "Westminster College",
  1884: "William Jewell College",
  1885: "William Woods University",
  1891: "Carroll College",
  1894: "Montana State University Billings",
  1899: "University of Providence",
  1903: "Montana Technological University",
  1904: "Montana State University",
  1905: "The University of Montana",
  1906: "Montana State University-Northern",
  1907: "Rocky Mountain College",
  1909: "The University of Montana-Western",
  1911: "Bellevue University",
  1912: "Clarkson College",
  1913: "Bryan College of Health Sciences",
  1915: "Chadron State College",
  1917: "Concordia University-Nebraska",
  1918: "Creighton University",
  1919: "Doane University",
  1920: "Hastings College",
  1923: "University of Nebraska at Kearney",
  1924: "Purdue University Global-Lincoln",
  1925: "Nebraska Methodist College of Nursing & Allied Health",
  1928: "Midland University",
  1929: "Nebraska Christian College of Hope International University",
  1930: "University of Nebraska at Omaha",
  1931: "Purdue University Global-Omaha",
  1933: "University of Nebraska Medical Center",
  1934: "Nebraska Wesleyan University",
  1935: "University of Nebraska-Lincoln",
  1937: "Peru State College",
  1939: "College of Saint Mary",
  1941: "Union College",
  1943: "Wayne State College",
  1945: "York College",
  1949: "The Art Institute of Las Vegas",
  1951: "University of Nevada-Las Vegas",
  1952: "University of Nevada-Reno",
  1954: "Sierra Nevada College",
  1957: "Colby-Sawyer College",
  1959: "Dartmouth College",
  1962: "Franklin Pierce University",
  1965: "Magdalen College",
  1967: "New England College",
  1969: "Southern New Hampshire University",
  1971: "University of New Hampshire-Main Campus",
  1972: "Keene State College",
  1973: "University of New Hampshire at Manchester",
  1974: "Plymouth State University",
  1983: "Rivier University",
  1984: "Saint Anselm College",
  1986: "Granite State College",
  1987: "Thomas More College of Liberal Arts",
  1993: "Berkeley College-Woodland Park",
  1994: "Beth Medrash Govoha",
  1995: "Bloomfield College",
  1998: "Caldwell University",
  2000: "Centenary University",
  2008: "Drew University",
  2012: "Fairleigh Dickinson University-Metropolitan Campus",
  2013: "Felician University",
  2014: "Fairleigh Dickinson University-Florham Campus",
  2016: "Georgian Court University",
  2017: "Rowan University",
  2024: "New Jersey City University",
  2026: "Kean University",
  2032: "Monmouth University",
  2033: "Montclair State University",
  2039: "New Jersey Institute of Technology",
  2046: "Princeton University",
  2047: "Rabbinical College of America",
  2048: "Ramapo College of New Jersey",
  2050: "Rider University",
  2051: "Rutgers University-Camden",
  2052: "Rutgers University-New Brunswick",
  2053: "Rutgers University-Newark",
  2056: "Saint Peter's University",
  2058: "Seton Hall University",
  2060: "College of Saint Elizabeth",
  2062: "Stevens Institute of Technology",
  2063: "Stockton University",
  2064: "Talmudical Academy-New Jersey",
  2066: "Thomas Edison State University",
  2067: "The College of New Jersey",
  2069: "William Paterson University of New Jersey",
  2075: "Eastern New Mexico University-Main Campus",
  2077: "Institute of American Indian and Alaska Native Culture and Arts Development",
  2078: "New Mexico Highlands University",
  2082: "New Mexico Institute of Mining and Technology",
  2084: "University of New Mexico-Main Campus",
  2088: "New Mexico State University-Main Campus",
  2093: "University of the Southwest",
  2099: "Western New Mexico University",
  2101: "Adelphi University",
  2104: "Albany College of Pharmacy and Health Sciences",
  2107: "Alfred University",
  2118: "Bard College",
  2119: "Barnard College",
  2121: "Berkeley College-New York",
  2123: "Beth Hatalmud Rabbinical College",
  2124: "Beth Hamedrash Shaarei Yosher Institute",
  2127: "Boricua College",
  2137: "Canisius College",
  2141: "Cazenovia College",
  2142: "Central Yeshiva Tomchei Tmimim Lubavitz",
  2147: "Clarkson University",
  2151: "Colgate University",
  2152: "Metropolitan College of New York",
  2153: "Columbia University in the City of New York",
  2156: "Concordia College-New York",
  2158: "Cooper Union for the Advancement of Science and Art",
  2159: "Cornell University",
  2164: "CUNY Bernard M Baruch College",
  2167: "CUNY Brooklyn College",
  2168: "College of Staten Island CUNY",
  2169: "CUNY City College",
  2170: "CUNY Graduate School and University Center",
  2172: "CUNY Hunter College",
  2173: "CUNY John Jay College of Criminal Justice",
  2176: "CUNY Lehman College",
  2177: "CUNY Medgar Evers College",
  2179: "CUNY Queens College",
  2182: "CUNY York College",
  2184: "D'Youville College",
  2185: "Daemen College",
  2186: "Yeshiva of Far Rockaway Derech Ayson Rabbinical Seminary",
  2187: "Dominican College of Blauvelt",
  2191: "Elmira College",
  2195: "Five Towns College",
  2196: "Fordham University",
  2202: "Hamilton College",
  2203: "Hartwick College",
  2206: "Hilbert College",
  2207: "Hobart William Smith Colleges",
  2208: "Hofstra University",
  2209: "Houghton College",
  2212: "Iona College",
  2215: "Ithaca College",
  2219: "Jewish Theological Seminary of America",
  2220: "The Juilliard School",
  2221: "Kehilath Yakov Rabbinical Seminary",
  2222: "Keuka College",
  2223: "LIM College",
  2224: "Le Moyne College",
  2225: "Long Island University",
  2228: "Machzikei Hadath Rabbinical College",
  2230: "Manhattan College",
  2231: "Manhattan School of Music",
  2232: "Manhattanville College",
  2235: "Marist College",
  2236: "Marymount Manhattan College",
  2237: "Medaille College",
  2240: "Mercy College",
  2241: "Mesivta Torah Vodaath Rabbinical Seminary",
  2243: "Mesivtha Tifereth Jerusalem of America",
  2247: "Mirrer Yeshiva Cent Institute",
  2250: "Molloy College",
  2251: "Monroe College",
  2253: "Mount Saint Mary College",
  2255: "College of Mount Saint Vincent",
  2258: "Nazareth College",
  2260: "The College of New Rochelle",
  2261: "The New School",
  2268: "New York University",
  2270: "Niagara University",
  2274: "New York Institute of Technology",
  2275: "New York School of Interior Design",
  2276: "Nyack College",
  2281: "Pace University",
  2282: "Paul Smiths College of Arts and Science",
  2285: "Davis College",
  2286: "Pratt Institute-Main",
  2287: "Rabbinical Academy Mesivta Rabbi Chaim Berlin",
  2288: "Rabbinical College Bobover Yeshiva Bnei Zion",
  2291: "Rabbinical Seminary of America",
  2292: "Rensselaer Polytechnic Institute",
  2293: "Roberts Wesleyan College",
  2294: "Rochester Institute of Technology",
  2295: "University of Rochester",
  2299: "Russell Sage College",
  2301: "St Bonaventure University",
  2302: "St Francis College",
  2304: "St Lawrence University",
  2305: "The College of Saint Rose",
  2306: "St. Thomas Aquinas College",
  2308: "Sarah Lawrence College",
  2310: "Sh'or Yoshuv Rabbinical College",
  2311: "Siena College",
  2312: "Skidmore College",
  2313: "St. Joseph's College-New York",
  2314: "St. Joseph's College-Long Island",
  2317: "Saint John Fisher College",
  2319: "St John's University-New York",
  2325: "SUNY College of Agriculture and Technology at Cobleskill",
  2326: "Farmingdale State College",
  2328: "SUNY at Albany",
  2329: "Binghamton University",
  2330: "University at Buffalo",
  2331: "Stony Brook University",
  2332: "SUNY College of Environmental Science and Forestry",
  2333: "SUNY Polytechnic Institute",
  2334: "SUNY College at Brockport",
  2335: "SUNY Buffalo State",
  2336: "SUNY Cortland",
  2337: "SUNY at Fredonia",
  2338: "SUNY College at Geneseo",
  2339: "State University of New York at New Paltz",
  2340: "SUNY Oneonta",
  2341: "SUNY College at Oswego",
  2342: "SUNY College at Potsdam",
  2343: "SUNY at Purchase College",
  2345: "SUNY College at Old Westbury",
  2346: "SUNY College at Plattsburgh",
  2347: "SUNY Downstate Health Sciences University",
  2348: "SUNY Empire State College",
  2349: "SUNY Maritime College",
  2350: "Upstate Medical University",
  2352: "Syracuse University",
  2353: "Talmudical Seminary Oholei Torah",
  2354: "Talmudical Institute of Upstate New York",
  2357: "Torah Temimah Talmudical Seminary",
  2358: "Touro College",
  2362: "Union College",
  2364: "United Talmudical Seminary",
  2365: "United States Merchant Marine Academy",
  2366: "United States Military Academy",
  2367: "Utica College",
  2368: "Vassar College",
  2369: "Villa Maria College",
  2370: "School of Visual Arts",
  2371: "Wagner College",
  2372: "Webb Institute",
  2373: "Wells College",
  2378: "Yeshiva Karlin Stolin",
  2379: "Yeshiva Derech Chaim",
  2380: "Yeshiva of Nitra Rabbinical College",
  2381: "Yeshiva Shaar Hatorah",
  2382: "Yeshiva University",
  2383: "Yeshivath Viznitz",
  2387: "Appalachian State University",
  2389: "Barton College",
  2391: "Belmont Abbey College",
  2392: "Bennett College",
  2395: "Brevard College",
  2399: "Campbell University",
  2403: "Catawba College",
  2407: "Chowan University",
  2412: "Davidson College",
  2413: "Duke University",
  2415: "East Carolina University",
  2417: "Elizabeth City State University",
  2418: "Elon University",
  2420: "Fayetteville State University",
  2422: "Gardner-Webb University",
  2424: "Greensboro College",
  2425: "Guilford College",
  2430: "High Point University",
  2433: "Johnson C Smith University",
  2435: "Lees-McRae College",
  2437: "Lenoir-Rhyne University",
  2439: "Livingstone College",
  2441: "Mars Hill University",
  2445: "Meredith College",
  2446: "Methodist University",
  2451: "Montreat College",
  2452: "University of Mount Olive",
  2455: "North Carolina A & T State University",
  2456: "University of North Carolina at Asheville",
  2457: "University of North Carolina at Chapel Hill",
  2458: "University of North Carolina at Charlotte",
  2459: "University of North Carolina at Greensboro",
  2460: "North Carolina Central University",
  2461: "University of North Carolina School of the Arts",
  2462: "North Carolina State University at Raleigh",
  2463: "North Carolina Wesleyan College",
  2464: "University of North Carolina Wilmington",
  2466: "William Peace University",
  2467: "University of North Carolina at Pembroke",
  2468: "Pfeiffer University",
  2471: "Queens University of Charlotte",
  2474: "Mid-Atlantic Christian University",
  2479: "Saint Augustine's University",
  2480: "Salem College",
  2483: "Shaw University",
  2486: "St. Andrews University",
  2490: "Southeastern Baptist Theological Seminary",
  2495: "Wake Forest University",
  2497: "Warren Wilson College",
  2503: "Wingate University",
  2504: "Carolina Christian College",
  2506: "Winston-Salem State University",
  2507: "Western Carolina University",
  2510: "Dickinson State University",
  2513: "University of Jamestown",
  2516: "University of Mary",
  2517: "Mayville State University",
  2518: "Minot State University",
  2520: "University of North Dakota",
  2523: "North Dakota State University-Main Campus",
  2527: "Trinity Bible College and Graduate School",
  2530: "Valley City State University",
  2532: "The Art Institute of Cincinnati-AIC College of Design",
  2535: "University of Akron Main Campus",
  2537: "Allegheny Wesleyan College",
  2540: "Art Academy of Cincinnati",
  2542: "Ashland University",
  2547: "Baldwin Wallace University",
  2549: "Bluffton University",
  2552: "Bowling Green State University-Main Campus",
  2557: "Capital University",
  2558: "Case Western Reserve University",
  2559: "Cedarville University",
  2562: "Central State University",
  2565: "The Christ College of Nursing and Health Sciences",
  2566: "Cincinnati Christian University",
  2568: "University of Cincinnati-Main Campus",
  2572: "Ohio Christian University",
  2575: "Cleveland Institute of Art",
  2576: "Cleveland Institute of Music",
  2577: "Cleveland State University",
  2580: "Columbus College of Art and Design",
  2585: "University of Dayton",
  2586: "Defiance College",
  2587: "Denison University",
  2591: "The University of Findlay",
  2592: "Franklin University",
  2594: "Gods Bible School and College",
  2600: "Heidelberg University",
  2601: "Hiram College",
  2607: "John Carroll University",
  2616: "Kent State University at Kent",
  2618: "Kenyon College",
  2619: "Kettering College",
  2620: "Lake Erie College",
  2627: "Lourdes University",
  2628: "Malone University",
  2629: "Marietta College",
  2634: "Miami University-Hamilton",
  2635: "Miami University-Middletown",
  2636: "Miami University-Oxford",
  2639: "Mount Carmel College of Nursing",
  2640: "University of Mount Union",
  2641: "Mount Vernon Nazarene University",
  2642: "Mount Saint Joseph University",
  2644: "Muskingum University",
  2650: "Notre Dame College",
  2653: "Oberlin College",
  2655: "Ohio Dominican University",
  2656: "Ohio Northern University",
  2658: "Ohio State University-Lima Campus",
  2666: "Ohio State University-Main Campus",
  2671: "Ohio University-Main Campus",
  2675: "Ohio Wesleyan University",
  2676: "Otterbein University",
  2681: "Pontifical College Josephinum",
  2684: "Rabbinical College Telshe",
  2689: "Shawnee State University",
  2694: "Franciscan University of Steubenville",
  2698: "Tiffin University",
  2699: "University of Toledo",
  2700: "Tri-State Bible College",
  2703: "Union Institute & University",
  2706: "Urbana University",
  2707: "Ursuline College",
  2709: "Walsh University",
  2711: "Wilberforce University",
  2712: "Wilmington College",
  2714: "Wittenberg University",
  2715: "The College of Wooster",
  2716: "Wright State University-Main Campus",
  2717: "Wright State University-Lake Campus",
  2718: "Xavier University",
  2719: "Youngstown State University",
  2720: "Bacone College",
  2721: "Oklahoma Wesleyan University",
  2722: "Southern Nazarene University",
  2725: "Cameron University",
  2728: "University of Central Oklahoma",
  2730: "East Central University",
  2735: "Randall University",
  2736: "Langston University",
  2739: "Northeastern State University",
  2743: "Northwestern Oklahoma State University",
  2745: "Oklahoma Christian University",
  2746: "University of Oklahoma-Health Sciences Center",
  2747: "Oklahoma Panhandle State University",
  2748: "Oklahoma State University-Main Campus",
  2750: "Oklahoma Baptist University",
  2752: "Oklahoma City University",
  2753: "University of Oklahoma-Norman Campus",
  2755: "Oral Roberts University",
  2756: "Rogers State University",
  2759: "University of Science and Arts of Oklahoma",
  2762: "Southeastern Oklahoma State University",
  2763: "Southwestern Christian University",
  2764: "Southwestern Oklahoma State University",
  2767: "University of Tulsa",
  2780: "Concordia University-Portland",
  2783: "Eastern Oregon University",
  2784: "New Hope Christian College-Eugene",
  2785: "George Fox University",
  2788: "Lewis & Clark College",
  2789: "Linfield College-McMinnville Campus",
  2794: "Mount Angel Seminary",
  2796: "Multnomah University",
  2797: "National University of Natural Medicine",
  2798: "Northwest Christian University",
  2799: "Oregon Health & Science University",
  2800: "Oregon Institute of Technology",
  2801: "Oregon College of Art and Craft",
  2802: "Oregon State University",
  2803: "University of Oregon",
  2804: "Pacific Northwest College of Art",
  2805: "Pacific University",
  2812: "Portland State University",
  2813: "University of Portland",
  2814: "Reed College",
  2817: "Southern Oregon University",
  2821: "Warner Pacific University",
  2822: "Corban University",
  2825: "Willamette University",
  2826: "Western Oregon University",
  2827: "University of Western States",
  2829: "Bryn Athyn College of the New Church",
  2831: "Albright College",
  2834: "Allegheny College",
  2836: "DeSales University",
  2838: "Alvernia University",
  2842: "Clarks Summit University",
  2844: "Arcadia University",
  2847: "Bloomsburg University of Pennsylvania",
  2848: "Bryn Mawr College",
  2849: "Bucknell University",
  2854: "Cabrini University",
  2855: "California University of Pennsylvania",
  2856: "Carlow University",
  2857: "Carnegie Mellon University",
  2858: "Cedar Crest College",
  2859: "Central Penn College",
  2860: "Chatham University",
  2861: "Chestnut Hill College",
  2862: "Cheyney University of Pennsylvania",
  2864: "Clarion University of Pennsylvania",
  2866: "Curtis Institute of Music",
  2869: "Delaware Valley University",
  2870: "Dickinson College",
  2873: "Drexel University",
  2874: "Duquesne University",
  2875: "East Stroudsburg University of Pennsylvania",
  2876: "Eastern University",
  2877: "Edinboro University of Pennsylvania",
  2878: "Elizabethtown College",
  2892: "Faith Theological Seminary",
  2894: "Franklin and Marshall College",
  2895: "Gannon University",
  2896: "Geneva College",
  2897: "Gettysburg College",
  2899: "Gratz College",
  2900: "Grove City College",
  2901: "Gwynedd Mercy University",
  2904: "Haverford College",
  2906: "Holy Family University",
  2907: "Hussian College-Philadelphia",
  2908: "Immaculata University",
  2909: "Indiana University of Pennsylvania-Main Campus",
  2914: "Juniata College",
  2915: "Keystone College",
  2916: "King's College",
  2918: "Kutztown University of Pennsylvania",
  2919: "La Roche University",
  2920: "La Salle University",
  2922: "Lafayette College",
  2923: "Lancaster Bible College",
  2928: "Lebanon Valley College",
  2931: "Lehigh University",
  2935: "Lincoln University",
  2936: "Lock Haven University",
  2940: "Lycoming College",
  2942: "Mansfield University of Pennsylvania",
  2943: "Marywood University",
  2946: "Mercyhurst University",
  2947: "Messiah University",
  2949: "Millersville University of Pennsylvania",
  2950: "Misericordia University",
  2952: "Moore College of Art and Design",
  2953: "Moravian College",
  2954: "Mount Aloysius College",
  2955: "Muhlenberg College",
  2956: "Neumann University",
  2963: "Pennsylvania State University-Penn State Erie-Behrend College",
  2966: "Pennsylvania State University-Penn State New Kensington",
  2967: "Pennsylvania State University-Penn State Shenango",
  2968: "Pennsylvania State University-Penn State Wilkes-Barre",
  2969: "Pennsylvania State University-Penn State Scranton",
  2970: "Pennsylvania State University-Penn State Lehigh Valley",
  2971: "Pennsylvania State University-Penn State Altoona",
  2972: "Pennsylvania State University-Penn State Beaver",
  2973: "Pennsylvania State University-Penn State Berks",
  2974: "Pennsylvania State University-Penn State Harrisburg",
  2975: "Pennsylvania State University-Penn State Brandywine",
  2977: "Pennsylvania State University-Penn State Fayette- Eberly",
  2978: "Pennsylvania State University-Penn State Hazleton",
  2979: "Pennsylvania State University-Main Campus",
  2980: "Pennsylvania State University-Penn State Greater Allegheny",
  2981: "Pennsylvania State University-Penn State Mont Alto",
  2982: "Pennsylvania State University-Penn State Abington",
  2983: "Pennsylvania State University-Penn State Schuylkill",
  2984: "Pennsylvania State University-Penn State York",
  2985: "Peirce College",
  2988: "Pennsylvania Academy of the Fine Arts",
  2991: "Pennsylvania College of Art and Design",
  2992: "University of Pennsylvania",
  2993: "The University of the Arts",
  2994: "Cairn University-Langhorne",
  2996: "University of the Sciences",
  2998: "University of Pittsburgh-Bradford",
  2999: "University of Pittsburgh-Greensburg",
  3000: "University of Pittsburgh-Johnstown",
  3001: "University of Pittsburgh-Pittsburgh Campus",
  3008: "Point Park University",
  3016: "Robert Morris University",
  3018: "Rosemont College",
  3019: "Saint Francis University",
  3020: "Saint Joseph's University",
  3021: "Saint Vincent College",
  3024: "University of Scranton",
  3025: "Seton Hill University",
  3029: "Shippensburg University of Pennsylvania",
  3030: "Slippery Rock University of Pennsylvania",
  3031: "Saint Charles Borromeo Seminary-Overbrook",
  3036: "Susquehanna University",
  3037: "Swarthmore College",
  3039: "Talmudical Yeshiva of Philadelphia",
  3040: "Temple University",
  3042: "Thiel College",
  3043: "Thomas Jefferson University",
  3050: "Ursinus College",
  3051: "University of Valley Forge",
  3054: "Villanova University",
  3056: "Washington & Jefferson College",
  3057: "Waynesburg University",
  3059: "West Chester University of Pennsylvania",
  3062: "Westminster College",
  3065: "Widener University",
  3066: "Wilkes University",
  3068: "Wilson College",
  3069: "Yeshivath Beth Moshe",
  3070: "York College of Pennsylvania",
  3072: "Brown University",
  3073: "Bryant University",
  3074: "Johnson & Wales University-Providence",
  3077: "Providence College",
  3078: "Rhode Island College",
  3080: "University of Rhode Island",
  3081: "Rhode Island School of Design",
  3082: "Roger Williams University",
  3083: "Salve Regina University",
  3086: "Northpoint Bible College",
  3088: "Allen University",
  3089: "Anderson University",
  3090: "Charleston Southern University",
  3092: "Benedict College",
  3093: "Bob Jones University",
  3094: "Southern Wesleyan University",
  3096: "College of Charleston",
  3099: "Citadel Military College of South Carolina",
  3100: "Claflin University",
  3101: "Clemson University",
  3102: "Clinton College",
  3103: "Coker University",
  3104: "Columbia International University",
  3105: "Columbia College",
  3106: "Converse College",
  3108: "Erskine College",
  3111: "Francis Marion University",
  3112: "Furman University",
  3117: "Lander University",
  3118: "Limestone College",
  3119: "Medical University of South Carolina",
  3121: "Morris College",
  3122: "Newberry College",
  3123: "North Greenville University",
  3126: "Presbyterian College",
  3127: "University of South Carolina Aiken",
  3128: "University of South Carolina Beaufort",
  3129: "University of South Carolina-Columbia",
  3134: "Coastal Carolina University",
  3135: "South Carolina State University",
  3136: "University of South Carolina-Upstate",
  3144: "Voorhees College",
  3146: "Winthrop University",
  3147: "Wofford College",
  3149: "Augustana University",
  3151: "Black Hills State University",
  3152: "Dakota State University",
  3153: "Dakota Wesleyan University",
  3158: "Mount Marty College",
  3159: "National American University-Rapid City",
  3160: "National American University-Sioux Falls",
  3162: "Northern State University",
  3163: "Oglala Lakota College",
  3164: "Presentation College",
  3166: "South Dakota School of Mines and Technology",
  3167: "South Dakota State University",
  3169: "University of Sioux Falls",
  3174: "University of South Dakota",
  3176: "American Baptist College",
  3179: "Austin Peay State University",
  3180: "Baptist Memorial College of Health Sciences",
  3181: "Belmont University",
  3182: "Bethel University",
  3183: "Bryan College-Dayton",
  3184: "Carson-Newman University",
  3186: "Christian Brothers University",
  3193: "Cumberland University",
  3194: "Lipscomb University",
  3198: "East Tennessee State University",
  3202: "Fisk University",
  3203: "Welch College",
  3204: "Freed-Hardeman University",
  3207: "Hiwassee College",
  3212: "Johnson University",
  3214: "King University",
  3216: "Lane College",
  3217: "Le Moyne-Owen College",
  3218: "Lee University",
  3219: "Lincoln Memorial University",
  3221: "Martin Methodist College",
  3222: "Maryville College",
  3226: "Memphis College of Art",
  3228: "University of Memphis",
  3230: "Middle Tennessee State University",
  3241: "Rhodes College",
  3247: "The University of the South",
  3255: "Southern Adventist University",
  3257: "Tennessee Wesleyan University",
  3258: "The University of Tennessee-Chattanooga",
  3259: "The University of Tennessee-Knoxville",
  3260: "The University of Tennessee-Martin",
  3262: "Tennessee State University",
  3263: "Tennessee Technological University",
  3264: "Trevecca Nazarene University",
  3266: "Tusculum University",
  3267: "Union University",
  3268: "Vanderbilt University",
  3272: "Abilene Christian University",
  3275: "Amberton University",
  3277: "Angelo State University",
  3278: "Arlington Baptist University",
  3280: "The Art Institute of Houston",
  3281: "Austin College",
  3286: "Baptist Missionary Association Theological Seminary",
  3288: "Baylor University",
  3300: "Concordia University Texas",
  3303: "Texas A & M University-Corpus Christi",
  3305: "Dallas Baptist University",
  3306: "Dallas Christian College",
  3309: "University of Dallas",
  3311: "East Texas Baptist University",
  3312: "Texas A&M University-Texarkana",
  3313: "Texas A & M University-Commerce",
  3321: "Miami International University of Art & Design-Art Institute Dallas",
  3327: "Hardin-Simmons University",
  3330: "Houston Baptist University",
  3331: "University of Houston-Clear Lake",
  3333: "University of Houston-Downtown",
  3334: "University of Houston-Victoria",
  3335: "University of Houston",
  3337: "Howard Payne University",
  3338: "Huston-Tillotson University",
  3339: "University of the Incarnate Word",
  3343: "Jarvis Christian College",
  3346: "Lamar University",
  3351: "Texas A & M International University",
  3353: "LeTourneau University",
  3355: "Lubbock Christian University",
  3357: "University of Mary Hardin-Baylor",
  3359: "McMurry University",
  3362: "Midwestern State University",
  3372: "University of North Texas",
  3379: "Our Lady of the Lake University",
  3380: "The University of Texas Rio Grande Valley",
  3384: "Paul Quinn College",
  3385: "Prairie View A & M University",
  3388: "Rice University",
  3390: "Saint Edward's University",
  3392: "University of St Thomas",
  3393: "Sam Houston State University",
  3396: "Schreiner University",
  3398: "St. Mary's University",
  3404: "Southern Methodist University",
  3407: "Southwestern Assemblies of God University",
  3408: "Southwestern University",
  3409: "Stephen F Austin State University",
  3410: "Texas State University",
  3411: "Southwestern Adventist University",
  3413: "Sul Ross State University",
  3414: "Tarleton State University",
  3418: "The University of Texas Health Science Center at San Antonio",
  3419: "The University of Texas Medical Branch at Galveston",
  3421: "Texas A & M University-Kingsville",
  3422: "Texas A & M University-College Station",
  3423: "The University of Texas at Arlington",
  3424: "The University of Texas at Austin",
  3425: "The University of Texas at Dallas",
  3426: "The University of Texas at El Paso",
  3427: "The University of Texas at Tyler",
  3429: "Texas Christian University",
  3430: "Texas College",
  3432: "Texas Lutheran University",
  3433: "The University of Texas of the Permian Basin",
  3434: "The University of Texas at San Antonio",
  3435: "Texas Southern University",
  3436: "Texas Tech University",
  3437: "Texas Wesleyan University",
  3438: "Texas Woman's University",
  3439: "Trinity University",
  3440: "The University of Texas Health Science Center at Houston",
  3441: "Texas Tech University Health Sciences Center",
  3449: "Wayland Baptist University",
  3451: "West Texas A & M University",
  3454: "Wiley College",
  3457: "Brigham Young University-Provo",
  3458: "Brigham Young University-Hawaii",
  3471: "Southern Utah University",
  3473: "Stevens-Henager College",
  3475: "Utah State University",
  3476: "Utah Valley University",
  3478: "University of Utah",
  3480: "Westminster College",
  3481: "Bennington College",
  3482: "Castleton University",
  3483: "Champlain College",
  3485: "Goddard College",
  3486: "Green Mountain College",
  3487: "Northern Vermont University",
  3488: "Marlboro College",
  3489: "Middlebury College",
  3490: "New England Culinary Institute",
  3491: "Norwich University",
  3493: "Saint Michael's College",
  3495: "College of St Joseph",
  3496: "Southern Vermont College",
  3497: "Sterling College",
  3500: "University of Vermont",
  3503: "Averett University",
  3505: "Bluefield College",
  3506: "Bridgewater College",
  3507: "William & Mary",
  3508: "Regent University",
  3511: "Christopher Newport University",
  3515: "Radford University-Carilion",
  3520: "Emory & Henry College",
  3521: "Eastern Mennonite University",
  3523: "Ferrum College",
  3524: "George Mason University",
  3526: "Hampden-Sydney College",
  3527: "Hampton University",
  3528: "Hollins University",
  3530: "James Madison University",
  3532: "Liberty University",
  3533: "Longwood University",
  3535: "University of Lynchburg",
  3537: "Mary Baldwin University",
  3538: "University of Mary Washington",
  3539: "Marymount University",
  3544: "Sentara College of Health Sciences",
  3546: "Norfolk State University",
  3548: "Old Dominion University",
  3553: "Radford University",
  3555: "Randolph-Macon College",
  3556: "Randolph College",
  3560: "Bon Secours Memorial College of Nursing",
  3561: "University of Richmond",
  3563: "Roanoke College",
  3565: "Shenandoah University",
  3566: "Southern Virginia University",
  3570: "Strayer University-Virginia",
  3571: "Sweet Briar College",
  3575: "The University of Virginia's College at Wise",
  3577: "Virginia Polytechnic Institute and State University",
  3579: "Virginia Commonwealth University",
  3580: "University of Virginia-Main Campus",
  3581: "Virginia Military Institute",
  3584: "Virginia State University",
  3585: "Virginia Union University",
  3586: "Virginia Wesleyan University",
  3587: "Washington and Lee University",
  3592: "Central Washington University",
  3594: "City University of Seattle",
  3599: "Cornish College of the Arts",
  3601: "Eastern Washington University",
  3605: "The Evergreen State College",
  3608: "Gonzaga University",
  3612: "Heritage University",
  3615: "Bastyr University",
  3622: "Northwest University",
  3625: "Pacific Lutheran University",
  3627: "University of Puget Sound",
  3629: "Saint Martin's University",
  3632: "Seattle Pacific University",
  3633: "Seattle University",
  3642: "Walla Walla University",
  3643: "Washington State University",
  3644: "University of Washington-Seattle Campus",
  3646: "Western Washington University",
  3648: "Whitman College",
  3649: "Whitworth University",
  3651: "Alderson Broaddus University",
  3653: "Appalachian Bible College",
  3656: "Bethany College",
  3657: "Bluefield State College",
  3660: "University of Charleston",
  3662: "Concord University",
  3663: "Davis & Elkins College",
  3664: "Fairmont State University",
  3669: "Marshall University",
  3675: "Ohio Valley University",
  3679: "Salem University",
  3680: "Shepherd University",
  3684: "West Virginia State University",
  3686: "West Liberty University",
  3687: "West Virginia University Institute of Technology",
  3688: "West Virginia Wesleyan College",
  3693: "West Virginia University",
  3694: "Wheeling University",
  3697: "Alverno College",
  3699: "Bellin College",
  3700: "Beloit College",
  3702: "Cardinal Stritch University",
  3703: "Carroll University",
  3704: "Carthage College",
  3705: "Columbia College of Nursing",
  3706: "Concordia University-Wisconsin",
  3707: "Edgewood College",
  3711: "Lakeland University",
  3713: "Lawrence University",
  3714: "Maranatha Baptist University",
  3715: "Marian University",
  3716: "Marquette University",
  3720: "Milwaukee Institute of Art & Design",
  3721: "Milwaukee School of Engineering",
  3723: "Mount Mary University",
  3728: "Northland College",
  3729: "Ripon College",
  3731: "Saint Norbert College",
  3732: "Holy Family College",
  3735: "Viterbo University",
  3739: "University of Wisconsin-Whitewater",
  3742: "University of Wisconsin-Eau Claire",
  3743: "University of Wisconsin-Green Bay",
  3744: "University of Wisconsin-La Crosse",
  3745: "Wisconsin Lutheran College",
  3746: "University of Wisconsin-Oshkosh",
  3747: "University of Wisconsin-Parkside",
  3749: "University of Wisconsin-Stout",
  3750: "University of Wisconsin-Superior",
  3751: "University of Wisconsin-Madison",
  3752: "University of Wisconsin-Milwaukee",
  3753: "University of Wisconsin-Platteville",
  3754: "University of Wisconsin-River Falls",
  3755: "University of Wisconsin-Stevens Point",
  3765: "University of Wyoming",
  3768: "University of Guam",
  3772: "American University of Puerto Rico",
  3773: "American University of Puerto Rico",
  3775: "Universidad Adventista de las Antillas",
  3776: "Atlantic University College",
  3777: "Universidad Central de Bayamon",
  3779: "Carlos Albizu University-San Juan",
  3780: "Caribbean University-Bayamon",
  3781: "Caribbean University-Carolina",
  3782: "Pontifical Catholic University of Puerto Rico-Arecibo",
  3783: "Pontifical Catholic University of Puerto Rico-Ponce",
  3784: "CEM College-San Juan",
  3785: "Universidad Teologica del Caribe",
  3787: "Universidad Ana G. Mendez-Cupey Campus",
  3788: "Conservatory of Music of Puerto Rico",
  3792: "Escuela de Artes Plasticas y Diseno de Puerto Rico",
  3803: "Inter American University of Puerto Rico-San German",
  3804: "Inter American University of Puerto Rico-Aguadilla",
  3805: "Inter American University of Puerto Rico-Arecibo",
  3806: "Inter American University of Puerto Rico-Barranquitas",
  3807: "Inter American University of Puerto Rico-Metro",
  3808: "Inter American University of Puerto Rico-Ponce",
  3809: "Inter American University of Puerto Rico-Fajardo",
  3810: "Inter American University of Puerto Rico-Guayama",
  3811: "Inter American University of Puerto Rico-Bayamon",
  3817: "National University College",
  3820: "University of Puerto Rico-Aguadilla",
  3821: "University of Puerto Rico-Arecibo",
  3822: "University of Puerto Rico-Bayamon",
  3823: "University of Puerto Rico-Carolina",
  3824: "University of Puerto Rico-Cayey",
  3825: "University of Puerto Rico-Humacao",
  3827: "University of Puerto Rico-Mayaguez",
  3828: "University of Puerto Rico-Medical Sciences",
  3829: "University of Puerto Rico-Ponce",
  3830: "University of Puerto Rico-Rio Piedras",
  3831: "Universidad Ana G. Mendez-Carolina Campus",
  3832: "Universidad del Sagrado Corazon",
  3835: "Universidad Politecnica de Puerto Rico",
  3836: "Pontifical Catholic University of Puerto Rico-Mayaguez",
  3837: "Universidad Ana G. Mendez-Gurabo Campus",
  3840: "University of the Virgin Islands",
  3841: "Stanford University",
  3842: "Purdue University-Main Campus",
  3858: "St. John's College",
  3859: "Bais Medrash Elyon",
  3860: "Antioch University-Los Angeles",
  3861: "Antioch University-Santa Barbara",
  3863: "Antioch University-Seattle",
  3864: "Antioch University-Midwest",
  3865: "Mid-America Christian University",
  3890: "Yeshiva Gedolah of Greater Detroit",
  3891: "Austin Graduate School of Theology",
  3916: "South University-Columbia",
  3923: "Platt College-Aurora",
  3924: "Purdue University Global-Davenport",
  3925: "Purdue University Global-Cedar Falls",
  3938: "Brandman University",
  3939: "New College of Florida",
  3954: "Yeshivah Gedolah Rabbinical College",
  3957: "Caribbean University-Ponce",
  3958: "Caribbean University-Vega Baja",
  3959: "University of Advancing Technology",
  3986: "South Florida Bible College and Theological Seminary",
  4005: "California State University-San Marcos",
  4018: "Hodges University",
  4027: "Nossi College of Art",
  4082: "Yeshiva Gedolah Imrei Yosef D'spinka",
  4094: "CEM College-Humacao",
  4114: "Northwest College of Art & Design",
  4115: "University of Washington-Bothell Campus",
  4116: "University of Washington-Tacoma Campus",
  4136: "University of Phoenix-Utah",
  4175: "Beacon College",
  4179: "University of the Potomac-Washington DC Campus",
  4180: "Rabbi Jacob Joseph School",
  4184: "Everglades University",
  4189: "College of Biblical Studies-Houston",
  4199: "Watkins College of Art Design & Film",
  4206: "Mt Sierra College",
  4209: "Soka University of America",
  4212: "World Mission University",
  4217: "Southwest University of Visual Arts-Albuquerque",
  4225: "Schiller International University",
  4234: "Yeshivas Novominsk",
  4236: "Rabbinical College of Ohr Shimon Yisroel",
  4238: "University of Phoenix-New Mexico",
  4248: "Arizona State University-West",
  4288: "California State University-Monterey Bay",
  4315: "Johnson & Wales University-North Miami",
  4317: "Trine University-Regional/Non-Traditional Campuses",
  4325: "The University of Texas MD Anderson Cancer Center",
  4349: "Messenger College",
  4421: "University of Phoenix-Hawaii",
  4426: "Yeshiva D'monsey Rabbinical College",
  4436: "Arizona State University-Polytechnic",
  4461: "Embry-Riddle Aeronautical University-Worldwide",
  4474: "Ottawa University-Milwaukee",
  4480: "Strayer University-Maryland",
  4489: "San Juan Bautista School of Medicine",
  4490: "Texas Health and Science University",
  4492: "New Hampshire Institute of Art",
  4518: "University of Phoenix-Washington",
  4523: "American University of Health Sciences",
  4534: "Florida Gulf Coast University",
  4559: "Yeshiva College of the Nations Capital",
  4560: "Louisiana State University Health Sciences Center-Shreveport",
  4571: "International Baptist College and Seminary",
  4579: "University of Management and Technology",
  4582: "Linfield College-School of Nursing",
  4583: "Linfield College-Online and Continuing Education",
  4595: "Stevens-Henager College",
  4603: "American InterContinental University-Atlanta",
  4614: "Johnson & Wales University-Denver",
  4617: "Atlantic Institute of Oriental Medicine",
  4624: "College of Biblical Studies",
  4628: "The King's University",
  4636: "Pacific Islands University",
  4651: "New Saint Andrews College",
  4653: "Marlboro College Graduate & Professional Studies",
  4656: "National American University-Ellsworth AFB Extension",
  4657: "National American University-Albuquerque West",
  4659: "Pillar College",
  4683: "Apex School of Theology",
  4687: "Yeshiva Shaarei Torah of Rockland",
  4693: "Universidad Pentecostal Mizpa",
  4701: "Nevada State College",
  4702: "California State University-Channel Islands",
  4703: "Franklin W Olin College of Engineering",
  4707: "University of Phoenix-Illinois",
  4721: "University of the Potomac-VA Campus",
  4723: "National American University-Overland Park",
  4731: "Birthingway College of Midwifery",
  4737: "Faith International University",
  4754: "West Coast University-Los Angeles",
  4755: "Williamson Christian College",
  4757: "DigiPen Institute of Technology",
  4760: "Dewey University-Hato Rey",
  4771: "Strayer University-Tennessee",
  4772: "Strayer University-Pennsylvania",
  4794: "Baptist University of the Americas",
  4796: "Beis Medrash Heichal Dovid",
  4814: "Charlotte Christian College and Theological Seminary",
  4825: "Flagler College-Tallahassee",
  4828: "American InterContinental University-Houston",
  4829: "University of California-Merced",
  4835: "Central Methodist University-College of Graduate and Extended Studies",
  4836: "University of Phoenix-New Jersey",
  4844: "Neumont College of Computer Science",
  4845: "Johnson & Wales University-Charlotte",
  4846: "Roseman University of Health Sciences",
  4859: "Ave Maria University",
  4869: "Ecclesia College",
  4877: "Maple Springs Baptist Bible College and Seminary",
  4886: "Uta Mesivta of Kiryas Joel",
  4887: "Harrisburg University of Science and Technology",
  4888: "Stevens-Henager College",
  4893: "United States University",
  4903: "SAE Expression College",
  4909: "Georgia Gwinnett College",
  4929: "SUM Bible College and Theological Seminary",
  4942: "Careers Unlimited",
  4946: "Doane University-Graduate and Professional Studies",
  4961: "University of South Florida-St Petersburg",
  4963: "Arizona State University-Downtown Phoenix",
  4967: "Strayer University-Florida",
  4972: "Dewey University-Juana Diaz",
  4994: "Bais Medrash Toras Chesed",
  5001: "Visible Music College",
  5008: "University of the West",
  5010: "South University-Tampa",
  5013: "Averett University-Non-Traditional Programs",
  5025: "Strayer University-Delaware",
  5027: "Strayer University-Alabama",
  5068: "Yeshivas Be'er Yitzchok",
  5069: "Yeshiva Toras Chaim",
  5070: "Talmudical Seminary of Bobov",
  5087: "University of South Florida-Sarasota-Manatee",
  5091: "The Art Institute of Austin",
  5107: "Strayer University-North Carolina",
  5108: "Strayer University-New Jersey",
  5112: "The King's College",
  5113: "Chamberlain University-Illinois",
  5114: "Chamberlain University-Ohio",
  5115: "Chamberlain University-Arizona",
  5136: "Aspen University",
  5139: "Denver College of Nursing",
  5170: "Yeshiva of Machzikai Hadas",
  5186: "The Chicago School of Professional Psychology at Los Angeles",
  5191: "Providence Christian College",
  5223: "Polytechnic University of Puerto Rico-Miami",
  5224: "Polytechnic University of Puerto Rico-Orlando",
  5233: "Strayer University-West Virginia",
  5238: "University of Minnesota-Rochester",
  5247: "Chamberlain University-Florida",
  5251: "Horizon University",
  5271: "Pacific Rim Christian University",
  5319: "Bethel College",
  5324: "West Coast University-Orange County",
  5325: "West Coast University-Ontario",
  5333: "The Art Institute of Virginia Beach",
  5343: "Strayer University-Arkansas",
  5344: "Strayer University-Georgia",
  5345: "Strayer University-Mississippi",
  5346: "Strayer University-South Carolina",
  5347: "Strayer University-Texas",
  5348: "The Art Institute of San Antonio",
  5366: "South University-Richmond",
  5367: "South University-Virginia Beach",
  5378: "Compass College of Cinematic Arts",
  5388: "Touro University Worldwide",
  5391: "Touro University Nevada",
  5392: "Herzing University-Kenosha",
  5393: "Herzing University-Brookfield",
  5394: "Texas A&M University-San Antonio",
  5398: "Strayer University-Global Region",
  5401: "California University of Management and Sciences",
  5413: "Fairfax University of America",
  5439: "Chamberlain University-Virginia",
  5450: "Carolina College of Biblical Studies",
  5487: "Bergin University of Canine Studies",
  5497: "North American University",
  5505: "Millennia Atlantic University",
  5526: "John Paul the Great Catholic University",
  5533: "Chamberlain University-Missouri",
  5534: "Chamberlain University-Texas",
  5540: "South University-Novi",
  5579: "Whitworth University-Adult Degree Programs",
  5581: "Springfield College-Regional Online and Continuing Education",
  5600: "Criswell College",
  5601: "Beverly Hills Design Institute",
  5608: "Chamberlain University-Georgia",
  5609: "Chamberlain University-Indiana",
  5626: "Bais HaMedrash and Mesivta of Baltimore",
  5631: "Yeshiva Gedolah Zichron Leyma",
  5633: "Be'er Yaakov Talmudic Seminary",
  5659: "West Coast University-Dallas",
  5683: "Purdue University Global-Augusta",
  5684: "South University-Austin",
  5685: "South University-Cleveland",
  5688: "Elizabethtown College School of Continuing and Professional Studies",
  5692: "Warner Pacific University Professional and Graduate Studies",
  5706: "California Miramar University",
  5715: "Gemini School of Visual Arts & Communication",
  5726: "Grace Mission University",
  5737: "Mid-South Christian College",
  5748: "Grace School of Theology",
  5749: "Yeshiva Gedolah Kesser Torah",
  5751: "Yeshiva Yesodei Hatorah",
  5764: "South University-High Point",
  5777: "Augusta University",
  5778: "Middle Georgia State University",
  5792: "DeVry College of New York",
  5793: "DeVry University-Arizona",
  5794: "DeVry University-California",
  5795: "DeVry University-Colorado",
  5796: "DeVry University-Florida",
  5797: "DeVry University-Georgia",
  5798: "DeVry University-Illinois",
  5799: "DeVry University-Indiana",
  5800: "DeVry University-Missouri",
  5801: "DeVry University-Nevada",
  5802: "DeVry University-New Jersey",
  5803: "DeVry University-North Carolina",
  5804: "DeVry University-Ohio",
  5805: "DeVry University-Pennsylvania",
  5806: "DeVry University-Tennessee",
  5807: "DeVry University-Texas",
  5808: "DeVry University-Virginia",
  5809: "University of North Georgia",
  5811: "Northeastern University Lifelong Learning Network",
  5812: "Florida Polytechnic University",
  5818: "Antioch College",
  5819: "Texas A&M University-Central Texas",
  5823: "Arizona State University-Skysong",
  5853: "IGlobal University",
  5900: "University of Phoenix-Arizona",
  5901: "University of Phoenix-California",
  5902: "University of Phoenix-Colorado",
  5903: "University of Phoenix-Florida",
  5904: "University of Phoenix-Georgia",
  5905: "University of Phoenix-Louisiana",
  5906: "University of Phoenix-Michigan",
  5907: "University of Phoenix-Nevada",
  5908: "University of Phoenix-North Carolina",
  5909: "University of Phoenix-Tennessee",
  5910: "University of Phoenix-Texas",
  5911: "University of Phoenix-Virginia",
  5912: "University of Phoenix-Pennsylvania",
  5914: "CEM College-Mayaguez",
  5916: "Rabbinical College Ohr Yisroel",
  5918: "University of North Texas at Dallas",
  5931: "West Coast University-Miami",
  5965: "Bet Medrash Gadol Ateret Torah",
  5966: "Yeshiva Gedola Ohr Yisrael",
  5967: "Yeshiva Sholom Shachna",
  5975: "Beth Medrash Meor Yitzchok",
  5994: "California Jazz Conservatory",
  6014: "Kennesaw State University",
  6019: "Milligan University",
  6020: "Chamberlain University-Nevada",
  6021: "Chamberlain University-Michigan",
  6025: "The University of Tennessee Health Science Center",
  6033: "University of Arizona-Sierra Vista",
  6051: "Husson University",
  6055: "Northwest University-College of Adult and Professional Studies",
  6060: "Yeshiva Zichron Aryeh",
  6077: "Central Yeshiva Beth Joseph",
  6086: "Yeshivas Maharit D'Satmar",
  6105: "Beth Medrash of Asbury Park",
  6119: "Indiana Wesleyan University-National & Global",
  6122: "Radiological Technologies University VT",
  6152: "Purdue University Global",
  6153: "Purdue University Global-Milwaukee",
  6157: "Piedmont International University",
  6159: "Presbyterian Theological Seminary in America",
  6161: "Southern States University",
  6163: "America Evangelical University",
  6168: "Westcliff University",
  6182: "Yeshiva Shaar Ephraim",
  6186: "Yeshiva Bais Aharon",
  6187: "Mechon L'hoyroa",
  6204: "Bais Medrash Mayan Hatorah",
  6216: "Purdue University Global-St. Louis",
  6217: "Purdue University Northwest",
  6221: "East-West University",
  6227: "Yeshiva Kollel Tifereth Elizer",
};

const names = Object.values(colleges);

export {names};